config/routes.rb
Workout::Application.routes.draw do
  resources :users

  resources :line_items

  match 'calendars/prev_month/:year/:month' => 'calendars#prev_month'
  match 'calendars/next_month/:year/:month' => 'calendars#next_month'
  resources :calendars

  get "home/index"

  resources :exercises

 

  root to: 'home#index', as: 'home'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  helper LaterDude::CalendarHelper 
  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
    @year = Time.now.year
    @month = Time.now.month

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendars }
    end
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/new
  # GET /calendars/new.json
  def new
    @calendar = Calendar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/1/edit
  def edit
    @calendar = Calendar.find(params[:id])
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(params[:calendar])

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render json: @calendar, status: :created, location: @calendar }
      else
        format.html { render action: "new" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calendars/1
  # PUT /calendars/1.json
  def update
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      if @calendar.update_attributes(params[:calendar])
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy

    respond_to do |format|
      format.html { redirect_to calendars_url }
      format.json { head :no_content }
    end
  end


  # PREV / calendars/1
  # PREV /calendars/1.json
  def prev_month
    @calendars = Calendar.all

    year = params[:year]
    month = params[:month]
    p_month = Time.new(year, month)-1.month

    @year = p_month.year
    @month = p_month.month

    respond_to do |format|
      format.html { render "index" }
      #format.json { render json: @calendars }
    end    
  end 

  # NEXT / calendars/1
  # NEXT /calendars/1.json
  def next_month
    @calendars = Calendar.all

    year = params[:year]
    month = params[:month]
    n_month = Time.new(year, month)+1.month

    @year = n_month.year
    @month = n_month.month

    respond_to do |format|
      format.html { render "index" }
      #format.json { render json: @calendars }
    end    
  end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1>Listing calendars</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calendars.each do |calendar| %>
  <tr>
    <td><%= button_to 'Previous Month', { action: 'prev_month', year: @year, month: @month }, method: :get %>
    <td><%= calendar_for( @year, @month, :calendar_class => "my_calendar", :use_full_day_names => true)%></td>
    <td><%= link_to 'Show', calendar %></td>
    <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
    <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= button_to 'Next Month', { action: 'next_month', year: @year, month: @month }, method: :get %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Calendar', new_calendar_path %>

<br />
<br />

<%= 'What Did I do on (enter date to see your past workouts!)' %>
  <select month="Month[value]"> 
    <option value="1">01</option> 
    <option value="2">02</option>
    <option value="3">03</option>
    <option value="4">04</option> 
    <option value="5">05</option>
    <option value="6">06</option>
    <option value="7">07</option>
    <option value="8">08</option>
    <option value="9">09</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option> 
  </select>

  <select day="Day[value]"> 
    <option value="1">01</option> <option value="2">02</option> <option value="3">03</option>
    <option value="4">04</option> <option value="5">05</option> <option value="6">06</option>
    <option value="7">07</option> <option value="8">08</option> <option value="9">09</option>
    <option value="10">10</option> <option value="11">11</option> <option value="12">12</option> 
    <option value="13">13</option> <option value="14">14</option> <option value="15">15</option>
    <option value="16">16</option> <option value="17">17</option> <option value="18">18</option>
    <option value="19">19</option> <option value="20">20</option> <option value="21">21</option>
    <option value="22">22</option> <option value="23">23</option> <option value="24">24</option>  
    <option value="25">25</option> <option value="26">26</option> <option value="27">27</option>
    <option value="28">28</option> <option value="29">29</option> <option value="30">30</option>
    <option value="31">31</option> 
  </select>

  <select year="Year[value]"> 
    <option value="2000">2000</option> 
    <option value="2001">2001</option>
    <option value="2002">2002</option>
    <option value="2003">2003</option> 
    <option value="2004">2004</option>
    <option value="2005">2005</option>
    <option value="2006">2006</option>
    <option value="2007">2007</option>
    <option value="2008">2008</option>
    <option value="2009">2009</option>
    <option value="2010">2010</option>
    <option value="2011">2011</option> 
    <option value="2012">2012</option>
    <option value="2013">2013</option>
    <option value="2014">2014</option>
  </select>

<%= '?' %>

<%= button_to 'Search!'%>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>