config/routes.rb
Workout::Application.routes.draw do
  resources :users

  resources :line_items

  match 'calendars/prev_month/:year/:month' => 'calendars#prev_month'
  match 'calendars/next_month/:year/:month' => 'calendars#next_month'
  resources :calendars

  get "home/index"

  resources :exercises

 

  root to: 'home#index', as: 'home'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.json
  def new
    @exercise = Exercise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render json: @exercise, status: :created, location: @exercise }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table>
<% @exercises.each do |exercise| %>
  <tr class="<% cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= image_tag(exercise.image_url, class: 'list_image') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= exercise.title %></dt>
        <dd><%= truncate(strip_tags(exercise.description), length:80) %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', exercise %><br/>
      <%= link_to 'Edit', edit_exercise_path(exercise) %><br/>
      <%= link_to 'Destroy', exercise, method: :delete, 
                   data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> title:</b>
  <%= @exercise. title %>
</p>

<p>
  <b>Description:</b>
  <%= @exercise.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @exercise.image_url %>
</p>


<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>